---
title: "QC2x2"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}


knitr::opts_chunk$set(echo = FALSE, results = 'asis', 
                      fig.height = 10, fig.width = 10,
                      eval = TRUE, message = FALSE, warning = FALSE)

# OS dependencies ----------------------------------------------------------


if(Sys.info()["sysname"] == "Linux"){
	data_path <- paste0("/media/",
			   system("whoami", intern = TRUE),
			   "/",
			   system(paste0("ls /media/",system("whoami", intern = TRUE)), intern = TRUE),
			   "/PSSJD/RESPOND/data/source/")
	data_path <- data_path[file.exists(data_path)]
	dev_lib_path <- "~/R/x86_64-pc-linux-gnu-library/dev"
} else if(Sys.info()["sysname"] == "Windows"){
	data_path <- paste0(grep("^[A-Z]:$", sub(":(.*)", ":",shell("wmic logicaldisk get name", intern = TRUE)), value = TRUE), "/PSSJD/RESPOND/data/source")
	data_path <- data_path[file.exists(data_path)]
	data_path <- paste0(data_path, "/")
	dev_lib_path <- .libPaths()
}



# Libraries ---------------------------------------------------------------

library(pander)
library(matrixStats)
library(data.table, lib.loc = dev_lib_path)






# Data loading --------------------------------------------------------------

load(paste0(data_path, "../target/BcnMadCE/CEdata2.rdata"))



# Data preparation  ----------------------------------------------------------------

Tlong[, `:=` (phq9_depression = factor(phq9 < 10, levels = c(FALSE, TRUE), labels = c("PHQ-9 >= 10", "PHQ-9 < 10")), gad7_anxiety = factor(gad7 < 10, levels = c(FALSE, TRUE), labels = c("GAD7 >= 10", "GAD7 < 10")))]
eTlong <- merge(screening, Tlong, all = TRUE, by.x = "Record_Id", by.y = "Castor_Record_ID")

eTlong[, `:=` (age = year(Survey_Completed_On) - t0_soc_02, 
	       to_soc_covid19 = fifelse(covid19_1 == "No", FALSE, TRUE), 
	       t0_soc_site = fifelse(Institute_Abbreviation == "SJD", "Bcn", "Mad"))
       ][, `:=` (baseline_phq_ads = phq_ads[wave == 1],
		 time = factor(wave, levels = 1:4, labels = c("T1. Baseline", "T2. Week 7 (post DWM)", "T3. Week 13 (post PM+)", "T4. Week 21 (follow-up)"))), 
       by = .(Record_Id)]

useNApar <- "no"

eTlong0 <- unique(eTlong[Institute_Abbreviation == "SJD", .(Record_Id)])
cols <- paste0("wave", 1:4)


```




# `covid19_1`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_1, wave)], Record_Id ~ wave, value.var = "covid19_1")[, table(T1 = `1`, T2 = `2`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "covid19_1 T1 vs T2", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_1, wave)], Record_Id ~ wave, value.var = "covid19_1")[, table(T2 = `2`, T3 = `3`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "covid19_1 T2 vs T3", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_1, wave)], Record_Id ~ wave, value.var = "covid19_1")[, table(T3 = `3`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "covid19_1 T3 vs T4", split.tables = Inf)

eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_1, wave)], Record_Id ~ paste0("wave",wave), value.var = "covid19_1")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (covid19_1_T1vsT2 = interaction(wave1, wave2, sep = "-"),
                                                                                                                                                                   covid19_1_T2vsT3 = interaction(wave2, wave3, sep = "-"),
                                                                                                                                                                   covid19_1_T3vsT4 = interaction(wave3, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")


```

# `covid19_01_1`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_01_1, wave)], Record_Id ~ wave, value.var = "covid19_01_1")[, table(T1 = `1`, T2 = `2`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "covid19_01_1 T1 vs T2", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_01_1, wave)], Record_Id ~ wave, value.var = "covid19_01_1")[, table(T2 = `2`, T3 = `3`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "covid19_01_1 T2 vs T3", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_01_1, wave)], Record_Id ~ wave, value.var = "covid19_01_1")[, table(T3 = `3`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "covid19_01_1 T3 vs T4", split.tables = Inf)

eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_01_1, wave)], Record_Id ~ paste0("wave",wave), value.var = "covid19_01_1")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (covid19_01_1_T1vsT2 = interaction(wave1, wave2, sep = "-"),
                                                                                                                                                                   covid19_01_1_T2vsT3 = interaction(wave2, wave3, sep = "-"),
                                                                                                                                                                   covid19_01_1_T3vsT4 = interaction(wave3, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")


```

# `covid19_4`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_4, wave)], Record_Id ~ wave, value.var = "covid19_4")[, table(T1 = `1`, T2 = `2`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "covid19_4 T1 vs T2", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_4, wave)], Record_Id ~ wave, value.var = "covid19_4")[, table(T2 = `2`, T3 = `3`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "covid19_4 T2 vs T3", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_4, wave)], Record_Id ~ wave, value.var = "covid19_4")[, table(T3 = `3`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "covid19_4 T3 vs T4", split.tables = Inf)


eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, covid19_4, wave)], Record_Id ~ paste0("wave",wave), value.var = "covid19_4")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (covid19_4_T1vsT2 = interaction(wave1, wave2, sep = "-"),
                                                                                                                                                                   covid19_4_T2vsT3 = interaction(wave2, wave3, sep = "-"),
                                                                                                                                                                   covid19_4_T3vsT4 = interaction(wave3, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```

# `le_1`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_1, wave)], Record_Id ~ wave, value.var = "le_1")[, table(T1 = `1`, T2 = `2`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "le_1 T1 vs T2", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_1, wave)], Record_Id ~ wave, value.var = "le_1")[, table(T2 = `2`, T3 = `3`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "le_1 T2 vs T3", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_1, wave)], Record_Id ~ wave, value.var = "le_1")[, table(T3 = `3`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "le_1 T3 vs T4", split.tables = Inf)

eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_1, wave)], Record_Id ~ paste0("wave",wave), value.var = "le_1")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (le_1_T1vsT2 = interaction(wave1, wave2, sep = "-"),
                                                                                                                                                                   le_1_T2vsT3 = interaction(wave2, wave3, sep = "-"),
                                                                                                                                                                   le_1_T3vsT4 = interaction(wave3, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```

# `le_2`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_2, wave)], Record_Id ~ wave, value.var = "le_2")[, table(T1 = `1`, T2 = `2`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "le_2 T1 vs T2", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_2, wave)], Record_Id ~ wave, value.var = "le_2")[, table(T2 = `2`, T3 = `3`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "le_2 T2 vs T3", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_2, wave)], Record_Id ~ wave, value.var = "le_2")[, table(T3 = `3`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "le_2 T3 vs T4", split.tables = Inf)

eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_2, wave)], Record_Id ~ paste0("wave",wave), value.var = "le_2")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (le_2_T1vsT2 = interaction(wave1, wave2, sep = "-"),
                                                                                                                                                                   le_2_T2vsT3 = interaction(wave2, wave3, sep = "-"),
                                                                                                                                                                   le_2_T3vsT4 = interaction(wave3, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```

# `le_3`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_3, wave)], Record_Id ~ wave, value.var = "le_3")[, table(T1 = `1`, T2 = `2`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "le_3 T1 vs T2", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_3, wave)], Record_Id ~ wave, value.var = "le_3")[, table(T2 = `2`, T3 = `3`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "le_3 T2 vs T3", split.tables = Inf)
dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_3, wave)], Record_Id ~ wave, value.var = "le_3")[, table(T3 = `3`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "le_3 T3 vs T4", split.tables = Inf)

eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, le_3, wave)], Record_Id ~ paste0("wave",wave), value.var = "le_3")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (le_3_T1vsT2 = interaction(wave1, wave2, sep = "-"),
                                                                                                                                                                   le_3_T2vsT3 = interaction(wave2, wave3, sep = "-"),
                                                                                                                                                                   le_3_T3vsT4 = interaction(wave3, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```

# `btq_01`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_01, wave)], Record_Id ~ wave, value.var = "btq_01")[, table(T1 = `1`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "btq_01 T1 vs T4", split.tables = Inf)


eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_01, wave)], Record_Id ~ paste0("wave",wave), value.var = "btq_01")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (btq_01_T1vsT4 = interaction(wave1, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```



# `btq_02`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_02, wave)], Record_Id ~ wave, value.var = "btq_02")[, table(T1 = `1`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "btq_02 T1 vs T4", split.tables = Inf)



eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_02, wave)], Record_Id ~ paste0("wave",wave), value.var = "btq_02")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (btq_02_T1vsT4 = interaction(wave1, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```



# `btq_03`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_03, wave)], Record_Id ~ wave, value.var = "btq_03")[, table(T1 = `1`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "btq_03 T1 vs T4", split.tables = Inf)



eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_03, wave)], Record_Id ~ paste0("wave",wave), value.var = "btq_03")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (btq_03_T1vsT4 = interaction(wave1, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```



# `btq_04`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_04, wave)], Record_Id ~ wave, value.var = "btq_04")[, table(T1 = `1`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "btq_04 T1 vs T4", split.tables = Inf)



eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_04, wave)], Record_Id ~ paste0("wave",wave), value.var = "btq_04")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (btq_04_T1vsT4 = interaction(wave1, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```



# `btq_05`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_05, wave)], Record_Id ~ wave, value.var = "btq_05")[, table(T1 = `1`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "btq_05 T1 vs T4", split.tables = Inf)



eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_05, wave)], Record_Id ~ paste0("wave",wave), value.var = "btq_05")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (btq_05_T1vsT4 = interaction(wave1, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```



# `btq_06`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_06, wave)], Record_Id ~ wave, value.var = "btq_06")[, table(T1 = `1`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "btq_06 T1 vs T4", split.tables = Inf)



eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_06, wave)], Record_Id ~ paste0("wave",wave), value.var = "btq_06")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (btq_06_T1vsT4 = interaction(wave1, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```



# `btq_07`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_07, wave)], Record_Id ~ wave, value.var = "btq_07")[, table(T1 = `1`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "btq_07 T1 vs T4", split.tables = Inf)



eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_07, wave)], Record_Id ~ paste0("wave",wave), value.var = "btq_07")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (btq_07_T1vsT4 = interaction(wave1, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```



# `btq_08`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_08, wave)], Record_Id ~ wave, value.var = "btq_08")[, table(T1 = `1`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "btq_08 T1 vs T4", split.tables = Inf)



eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_08, wave)], Record_Id ~ paste0("wave",wave), value.var = "btq_08")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (btq_08_T1vsT4 = interaction(wave1, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```



# `btq_09`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_09, wave)], Record_Id ~ wave, value.var = "btq_09")[, table(T1 = `1`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "btq_09 T1 vs T4", split.tables = Inf)



eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_09, wave)], Record_Id ~ paste0("wave",wave), value.var = "btq_09")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (btq_09_T1vsT4 = interaction(wave1, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```



# `btq_10`

```{r}

dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_10, wave)], Record_Id ~ wave, value.var = "btq_10")[, table(T1 = `1`, T4 = `4`, useNA = useNApar)] |> addmargins() |> ftable() |> pander(caption = "btq_10 T1 vs T4", split.tables = Inf)



eTlong0 <- merge(eTlong0,
                 dcast(eTlong[Institute_Abbreviation == "SJD", .(Record_Id, btq_10, wave)], Record_Id ~ paste0("wave",wave), value.var = "btq_10")[, (cols) := lapply(.SD, \(.x) substr(.x, 1, pmin(nchar(as.character(.x)), 20))), .SDcols = patterns("wave")
                                                                                                                                                         ][, `:=` (btq_10_T1vsT4 = interaction(wave1, wave4, sep = "-"))][, .SD, .SDcols = !patterns("wave")],
                 by = "Record_Id")



```



```{r}

fwrite(eTlong0, file = paste0(data_path, "../target/BcnMadCE/QC.csv"))

```

